name: construction_mate
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  intl: ^0.19.0
  http: ^1.2.1
  shimmer: ^3.0.0
  shared_preferences: ^2.2.3
  pdf: ^3.11.1
  path_provider: ^2.1.4
  printing: ^5.12.0
  freezed_annotation: ^2.4.4
  flutter_gen: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^3.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/logos/
    - assets/fonts/monteserrat/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Montserrat
      fonts:
        - asset: assets/fonts/monteserrat/Montserrat-Black.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/monteserrat/Montserrat-Bold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/monteserrat/Montserrat-Regular.ttf
          weight: 500
          style: normal
